Repository mo-moim/momoim-BE, pull requests merged in 2024-12, with the labels that each got.

#10 [MMM-6] Global exception handler 정의
  momoim-external-api/build.gradle
  momoim-support/build.gradle
  momoim-support/src/main/java/com/triplem/momoim/exception/BusinessException.java
  momoim-support/src/main/java/com/triplem/momoim/exception/ExceptionCode.java
  momoim-support/src/main/java/com/triplem/momoim/exception/ExceptionResponse.java
  momoim-support/src/main/java/com/triplem/momoim/exception/Temp.java
  momoim-support/src/main/java/com/triplem/momoim/handler/GlobalExceptionHandler.java
Labels: enhancement

#12 Mmm 11/feature/auth
  momoim-auth/build.gradle
  momoim-auth/src/main/java/com/triplem/momoim/auth/config/JwtAuthenticationEntryPoint.java
  momoim-auth/src/main/java/com/triplem/momoim/auth/config/UserAuthentication.java
  momoim-auth/src/main/java/com/triplem/momoim/auth/config/filter/JwtFilter.java
  momoim-auth/src/main/java/com/triplem/momoim/auth/config/handler/AuthExceptionHandler.java
  momoim-auth/src/main/java/com/triplem/momoim/auth/config/handler/CustomAccessDeniedHandler.java
  momoim-auth/src/main/java/com/triplem/momoim/auth/jwt/JwtResolver.java
  momoim-auth/src/main/java/com/triplem/momoim/auth/utils/SecurityUtil.java
  momoim-auth/src/main/java/com/triplem/momoim/auth/utils/StaticEndpointChecker.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserJpaRepository.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserRepository.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserRepositoryImpl.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/test/TestController.java
  momoim-external-api/src/main/java/com/triplem/momoim/config/CorsConfig.java
  momoim-external-api/src/main/java/com/triplem/momoim/config/SecurityConfig.java
  momoim-support/src/main/java/com/triplem/momoim/exception/ExceptionCode.java
Labels: enhancement

#21 [MMM-20] Auth domain에 대한 Swagger 명세 작성
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/controller/AuthController.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/request/SigninRequest.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/request/SignupRequest.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/request/UserProfileUpdateRequest.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/response/SigninResponse.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/response/SignupResponse.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/response/UserDetailResponse.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/response/common/Token.java
  momoim-external-api/src/main/java/com/triplem/momoim/config/SwaggerConfig.java
Labels: enhancement

#23 [HOTFIX] User profile 조회 API에 대한 method 수정
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/controller/AuthController.java
Labels: bug

#31 [MMM-27] Auth API 정의
  momoim-auth/src/main/java/com/triplem/momoim/auth/config/filter/JwtFilter.java
  momoim-core/build.gradle
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/User.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserActiveLocation.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserActiveLocationEntity.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserActiveLocationJpaRepository.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserActiveLocationRegister.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserActiveLocationRepository.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserActiveLocationRepositoryImpl.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserActiveLocationType.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserEntity.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserInterestCategoryImpl.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserInterestCategoryJpaRepository.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserInterestCategoryRegister.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserInterestCategoryRepository.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserJpaRepository.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserRepository.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserRepositoryImpl.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/controller/AuthController.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/request/SigninRequest.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/request/SignupRequest.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/response/SigninResponse.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/response/UserDetailResponse.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/service/AuthCommandService.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/service/AuthQueryService.java
  momoim-external-api/src/main/java/com/triplem/momoim/config/SecurityConfig.java
  momoim-support/src/main/java/com/triplem/momoim/exception/ExceptionCode.java
  momoim-support/src/main/java/com/triplem/momoim/handler/GlobalExceptionHandler.java
Labels: enhancement

#35 [MMM-33] 회원가입 시 같은 이메일로 가입을 시도할 경우 에러 반환 로직 반영
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserJpaRepository.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserRepository.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserRepositoryImpl.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/service/AuthCommandService.java
Labels: enhancement

#41 [MMM-39] S3 Configuration과 이미지와 관련된 API 정의
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserActiveLocationJpaRepository.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserActiveLocationRegister.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserActiveLocationRepository.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserActiveLocationRepositoryImpl.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserInterestCategoryImpl.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserInterestCategoryJpaRepository.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserInterestCategoryRegister.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserInterestCategoryRepository.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/controller/AuthController.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/request/UserProfileUpdateRequest.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/service/AuthCommandService.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/file/controller/S3FileController.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/file/response/PreSignedUrlResponse.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/file/service/FileQueryService.java
  momoim-infrastructure/build.gradle
  momoim-infrastructure/src/main/java/com/triplem/momoim/aws/s3/S3FileService.java
Labels: enhancement

#50 [MMM-49] Cors Origin 설정
  momoim-external-api/src/main/java/com/triplem/momoim/config/CorsConfig.java
Labels: enhancement

#52 [MMM-51] User profile에서 Guest에 대한 validation check 로직 반영건
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/service/AuthCommandService.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/service/AuthQueryService.java
Labels: enhancement

#66 [Hotfix] 새롭게 배포된 사이트의 도메인을 cors origin에 등록
  momoim-external-api/src/main/java/com/triplem/momoim/config/CorsConfig.java
Labels: bug, Infra

#68 [HOTFIX] Profile update시 subcategory 데이터를 포함
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserInterestCategory.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserInterestCategoryEntity.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserInterestCategoryRegister.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/request/UserProfileUpdateRequest.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/response/UserDetailResponse.java
Labels: enhancement

#72 [HOTFIX] sub category column nullable annotation
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserInterestCategoryEntity.java
Labels: bug

#73 [HOTFIX] 회원가입 시 Interest Category 저장 로직 변경건
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserInterestCategoryRegister.java
  momoim-support/src/main/java/com/triplem/momoim/exception/ExceptionCode.java
Labels: enhancement

#75 [MMM-74] Email, Nickname 중복 체크 API 정의
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserJpaRepository.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserRepository.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/user/UserRepositoryImpl.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/controller/AuthController.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/request/CheckEmailRequest.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/request/CheckNicknameRequest.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/response/CheckEmailNicknameResponse.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/service/AuthQueryService.java
  momoim-support/src/main/java/com/triplem/momoim/exception/ExceptionCode.java
Labels: enhancement

#77 리뷰 작성 가능한 모임 목록 조회 API / 모임 생성 API 기획 반영
  momoim-core/src/main/java/com/triplem/momoim/core/domain/gathering/infrastructure/GatheringEntity.java
  momoim-core/src/main/java/com/triplem/momoim/core/domain/review/infrastructure/ReviewRepositoryImpl.java
Labels: enhancement

#81 [MMM-80] Profile 관심 카테고리 응답 포맷 변경
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/response/SigninResponse.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/response/UserDetailResponse.java
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/service/TokenCommandService.java
Labels: enhancement

#82 [Hotfix] localhost시 cookie domain 설정 변경
  momoim-external-api/src/main/java/com/triplem/momoim/api/auth/service/TokenCommandService.java
Labels: enhancement
